(() => {
  const baseTheme = document.createElement('link');
  baseTheme.rel = 'stylesheet';
  baseTheme.href = 'm7-theme.css';
  document.head.appendChild(baseTheme);
  const hauntedTheme = document.createElement('link');
  hauntedTheme.rel = 'stylesheet';
  hauntedTheme.href = 'm7-haunted.css';
  document.head.appendChild(hauntedTheme);

  const allA=[...document.querySelectorAll('audio')];
  const status=document.querySelector('#playback-status'), master=document.querySelector('#master-audio'), timecode=document.querySelector('#timecode');
  const clear=()=>{allA.forEach(a=>{a.pause();a.currentTime=0});if(master){master.pause();master.currentTime=0}document.querySelectorAll('.track,.record-row').forEach(x=>x.classList.remove('active'));if(status)status.textContent='STANDBY'};
  const active=x=>{document.querySelectorAll('.track,.record-row').forEach(y=>y.classList.remove('active'));if(x)x.classList.add('active')};
  allA.forEach(a=>{a.addEventListener('play',()=>{allA.forEach(b=>{if(b!==a)b.pause()});active(a.closest('.track'));if(status)status.textContent='PLAYING'});a.addEventListener('ended',()=>{if(status)status.textContent='END / COPY RETAINED'})});
  document.querySelectorAll('.side-tab').forEach(t=>t.addEventListener('click',()=>{const s=t.dataset.side;document.querySelectorAll('.side-tab').forEach(x=>{const on=x.dataset.side===s;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))});document.querySelectorAll('[data-side-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.sidePanel!==s))}));
  document.querySelectorAll('.load-track').forEach(b=>b.addEventListener('click',()=>{const r=b.closest('.track'),a=r?.querySelector('audio');if(a){a.play().catch(()=>{});active(r)}}));
  if(master){document.querySelectorAll('.load-record').forEach(b=>b.addEventListener('click',()=>{clear();master.src=b.dataset.src||'';master.play().catch(()=>{});active(b.closest('.record-row'));if(status)status.textContent='PLAYING / '+(b.dataset.title||'RECORD')}));master.addEventListener('timeupdate',()=>{if(!timecode)return;const f=s=>{s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};timecode.textContent=`${f(master.currentTime)} / ${f(master.duration)}`});document.querySelector('#stop-all')?.addEventListener('click',clear);document.querySelector('#rewind')?.addEventListener('click',()=>master.currentTime=Math.max(0,master.currentTime-10));document.querySelector('#fast-forward')?.addEventListener('click',()=>master.currentTime=Math.min(master.duration||0,master.currentTime+10))}
  const home=document.querySelector('.home-page main');
  if(home&&!home.querySelector('.m7-quests')){const sec=document.createElement('section');sec.className='section wrap m7-quests';sec.innerHTML='<div class="section-head"><span>03 / 探索</span><h2 class="jp-display">QUESTS</h2><em>見つけたら、記録する。</em></div><div class="quest-grid"><button class="quest-card" data-quest="seven"><span>01</span><strong class="jp-display">七つ数える</strong><small>Find seven red marks, but do not count the one in the logo.</small><b>LOCKED</b></button><button class="quest-card" data-quest="two"><span>02</span><strong class="jp-display">音２を探す</strong><small>The missing designation appears where it should not.</small><b>LOCKED</b></button><button class="quest-card" data-quest="stop"><span>03</span><strong class="jp-display">停止記録</strong><small>Find the instruction for a stop that never happened.</small><b>LOCKED</b></button></div><div id="quest-message" class="quest-message">記録試験：待機中</div>';home.appendChild(sec)}
  const msg=document.querySelector('#quest-message');
  const done=n=>{localStorage.setItem('m7-'+n,'1');document.body.classList.add('quest-'+n);document.querySelectorAll(`[data-quest="${n}"]`).forEach(q=>{q.classList.add('found');q.querySelector('b')&&(q.querySelector('b').textContent='FOUND')})};
  document.querySelectorAll('[data-quest]').forEach(q=>q.addEventListener('click',()=>{const n=q.dataset.quest;if(n==='seven'){const found=document.querySelectorAll('.hill[data-found="1"]').length;if(found>=7)done(n);if(msg)msg.textContent=found>=7?'七つの印を確認。数えたのは丘ではない。':'赤い印を七つ探してください。ロゴは数えません。'}if(n==='two'){done(n);if(msg)msg.textContent='音２の参照を確認。資料そのものは存在しない。'}if(n==='stop'){done(n);if(msg)msg.textContent='停止命令を確認。停止時刻は記録されていない。'}}));
  document.querySelectorAll('.hill').forEach(h=>h.addEventListener('click',()=>{h.dataset.found='1';h.style.filter='brightness(1.85) drop-shadow(0 0 6px #8b2019)';if(document.querySelectorAll('.hill[data-found="1"]').length>=7){done('seven');if(msg)msg.textContent='七つの印を確認。次は、なぜ七つなのか。'}}));
  document.querySelectorAll('a,button').forEach(el=>{const t=(el.textContent||'').trim();if(/音2|音２/.test(t))el.addEventListener('click',()=>done('two'));if(/STOP|停止/.test(t))el.addEventListener('click',()=>done('stop'))});
  const turn=document.querySelector('.turn-note'),secret=document.querySelector('.secret-slip');if(turn&&secret)turn.addEventListener('click',()=>{secret.hidden=!secret.hidden;turn.textContent=secret.hidden?'TURN OVER':'RETURN FACE DOWN';done('stop')});
  const count=document.querySelector('#reveal-seven');if(count)count.addEventListener('click',()=>{const out=document.querySelector('#seven-result');if(out){out.textContent=localStorage.getItem('m7-count')==='six'?'六つ。':'六つ。もう一度。';localStorage.setItem('m7-count','six')}});
  document.querySelectorAll('[data-quest]').forEach(q=>{if(localStorage.getItem('m7-'+q.dataset.quest)){q.classList.add('found');q.querySelector('b')&&(q.querySelector('b').textContent='FOUND')}});
  const drawerLink=document.querySelector('[data-drawer-link]');if(drawerLink&&!(localStorage.getItem('m7-seven')||localStorage.getItem('m7-two')))drawerLink.setAttribute('aria-disabled','true');
  const drawerStatus=document.querySelector('#drawer-status');if(drawerStatus){const unlocked=localStorage.getItem('m7-seven')||localStorage.getItem('m7-two');drawerStatus.textContent=unlocked?'STATUS / OPEN — RECORDING CONTINUES':'STATUS / LOCKED — COUNT REQUIRED'}
  let logoClicks=0;const logo=document.querySelector('.brand img');if(logo)logo.addEventListener('click',()=>{logoClicks++;if(logoClicks===7){document.body.classList.add('archive-unlocked');const hidden=document.createElement('div');hidden.className='hidden-report';hidden.textContent='報告 0007 / 「七つ」は地理ではない。';document.body.appendChild(hidden)}});
  document.querySelectorAll('.object-scan img').forEach(img=>img.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();const overlay=document.createElement('div');overlay.className='asset-inspection';overlay.innerHTML=`<div class="inspection-paper"><button aria-label="close">×</button><div class="inspection-code">M7 / OBJECT INSPECTION</div><img src="${img.getAttribute('src')||''}" alt=""><p>IMAGE RETAINED / SOURCE FILE UNMODIFIED</p></div>`;document.body.appendChild(overlay);overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.tagName==='BUTTON')overlay.remove()})}));
})();
