(() => {
  const style=document.createElement('link');style.rel='stylesheet';style.href='m7-theme.css';style.dataset.m7Theme='1';document.head.appendChild(style);
  const allA=[...document.querySelectorAll('audio')];
  const status=document.querySelector('#playback-status'), master=document.querySelector('#master-audio'), timecode=document.querySelector('#timecode');
  const clear=()=>{allA.forEach(a=>{a.pause();a.currentTime=0});if(master){master.pause();master.currentTime=0}document.querySelectorAll('.track,.record-row').forEach(x=>x.classList.remove('active'));if(status)status.textContent='STANDBY'};
  const active=x=>{document.querySelectorAll('.track,.record-row').forEach(y=>y.classList.remove('active'));if(x)x.classList.add('active')};
  allA.forEach(a=>{a.addEventListener('play',()=>{allA.forEach(b=>{if(b!==a)b.pause()});active(a.closest('.track'));if(status)status.textContent='PLAYING'});a.addEventListener('ended',()=>{if(status)status.textContent='END / COPY RETAINED'})});
  document.querySelectorAll('.side-tab').forEach(t=>t.addEventListener('click',()=>{const s=t.dataset.side;document.querySelectorAll('.side-tab').forEach(x=>{const on=x.dataset.side===s;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))});document.querySelectorAll('[data-side-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.sidePanel!==s))}));
  document.querySelectorAll('.load-track').forEach(b=>b.addEventListener('click',()=>{const r=b.closest('.track'),a=r?.querySelector('audio');if(a){a.play().catch(()=>{});active(r)}}));
  if(master){document.querySelectorAll('.load-record').forEach(b=>b.addEventListener('click',()=>{clear();master.src=b.dataset.src||'';master.play().catch(()=>{});active(b.closest('.record-row'));if(status)status.textContent='PLAYING / '+(b.dataset.title||'RECORD')}));master.addEventListener('timeupdate',()=>{if(!timecode)return;const f=s=>{s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};timecode.textContent=`${f(master.currentTime)} / ${f(master.duration)}`});document.querySelector('#stop-all')?.addEventListener('click',clear);document.querySelector('#rewind')?.addEventListener('click',()=>master.currentTime=Math.max(0,master.currentTime-10));document.querySelector('#fast-forward')?.addEventListener('click',()=>master.currentTime=Math.min(master.duration||0,master.currentTime+10))}
  const msg=document.querySelector('#quest-message');
  const done=n=>{localStorage.setItem('m7-'+n,'1');document.querySelectorAll(`[data-quest="${n}"]`).forEach(q=>{q.classList.add('found');q.querySelector('b')&&(q.querySelector('b').textContent='FOUND')})};
  document.querySelectorAll('.hill').forEach(h=>h.addEventListener('click',()=>{h.dataset.found='1';h.style.filter='brightness(1.7) drop-shadow(0 0 5px #8b2019)';if(document.querySelectorAll('.hill[data-found="1"]').length>=7){done('seven');if(msg)msg.textContent='記録試験：七つの印を確認。次は、なぜ七つなのか。'}}));
  document.querySelectorAll('[data-quest]').forEach(q=>q.addEventListener('click',()=>{const n=q.dataset.quest;if(n==='seven'){done(n);if(msg)msg.textContent='赤い印を七つ探してください。';}if(n==='two'){done(n);if(msg)msg.textContent='音２への参照を確認。資料そのものは見つからない。';}if(n==='stop'){done(n);if(msg)msg.textContent='停止命令を確認。停止時刻は記録されていない。'}}));
  document.querySelectorAll('a,button').forEach(el=>{const t=(el.textContent||'').trim();if(/音2|音２/.test(t))el.addEventListener('click',()=>done('two'));if(/STOP|停止/.test(t))el.addEventListener('click',()=>done('stop'))});
  const turn=document.querySelector('.turn-note'),secret=document.querySelector('.secret-slip');if(turn&&secret)turn.addEventListener('click',()=>{secret.hidden=!secret.hidden;turn.textContent=secret.hidden?'TURN OVER':'RETURN FACE DOWN';done('stop')});
  const count=document.querySelector('#reveal-seven');if(count)count.addEventListener('click',()=>{const out=document.querySelector('#seven-result');if(out)out.textContent='六つ。もう一度。';localStorage.setItem('m7-count','six')});
  document.querySelectorAll('[data-quest]').forEach(q=>{if(localStorage.getItem('m7-'+q.dataset.quest)){q.classList.add('found');q.querySelector('b')&&(q.querySelector('b').textContent='FOUND')}});
  let logoClicks=0;const logo=document.querySelector('.brand img');if(logo)logo.addEventListener('click',()=>{logoClicks++;if(logoClicks===7){document.body.classList.add('archive-unlocked');if(msg)msg.textContent='0007 : 画面の裏側に記録がある。'}});
})();
